### ISSUE TITLE
[主页 > 常用工具 > 成分姬] placeholder提示文本错误，且api地址错误

### ISSUE THREAD

**Issue by wr786** [A-SoulFan/homepage-2.0#1]
https://github.com/A-SoulFan/homepage-2.0/blob/53094ef5061aba05d0f85d6a011187173227720f/src/components/commonTools/commonTools.vue#L23-L28

![image](https://user-images.githubusercontent.com/32223541/147313133-b07d72c1-6157-4ecd-a1b8-66cb9717a5a0.png)

如图，placeholder疑似是直接复制了词典而忘记修改了。

此外，在实用工具的成分姬页中可以正常使用成分姬，但是在主页上（就是上面那张图）中只会报错，经定位，原因是发送到了下面的这个api地址，而不是`https://api.asoulfan.com/cfj/`

https://github.com/A-SoulFan/homepage-2.0/blob/53094ef5061aba05d0f85d6a011187173227720f/src/components/commonTools/commonTools.vue#L241-L249

**Comment by Sanzenin-rentu** [comment]
小伙伴你好，感谢指出，前一段时间因为产能不足没有修，现在已经修复
